$schema: https://fiboa.github.io/schema/v0.1.0/schema.json
required:
  - ml:creation_method
  - ml:boundary_type
  - ml:verified_from
  - ml:verified_until
  - ml:author
  - ml:quality
  - ml:machine_generated
  - ml:country_code
  - ml:admin0
  - ml:admin1
  - ml:admin2
  - ml:crop_category
properties:
  ml:creation_method:
    type: string
  ml:creation_method_detail:
    type: string
  ml:ml:boundary_type:
    type: string
    required: true
  ml:creation_date:
    type: date-time
  ml:verified_from:
    type: date-time
  ml:verified_until:
    type: date-time
  ml:author:
    type: string
  ml:quality:
    type: string
  ml:confidence:
    type: float
  ml:machine_generated:
    type: boolean
  ml:country_code:
    type: string
  ml:admin0:
    type: string
  ml:admin1:
    type: string
  ml:admin2:
    type: string
  ml:crop_type:
    type: string
  ml:crop_category:
    type: string
