$schema: https://vecorel.org/sdl/v0.2.0/schema.json
# extensions:
#   - https://fiboa.org/specification/v0.3.0/schema.yaml
#   - https://vecorel.org/administrative-division-extension/v0.1.0/schema.yaml
required:
  - category
  - determination:method
  - determination:datetime
  - admin:country_code
  - admin:subdivision_code
  - ml:boundary_type
  - ml:creation_date
  - ml:verified_from
  - ml:author
properties:
  ml:boundary_type:
    type: string
    enum:
      - field
      - parcel
      - hedge
      - other
  ml:creation_date:
    type: date
  ml:verified_from:
    type: date
  ml:author:
    type: string
  ml:admin2:
    type: string
    minLength: 1
    maxLength: 2
    pattern: ^[A-Z0-9]{1,2}$
