$schema: https://fiboa.github.io/schema/v0.1.0/schema.json
required:
  - ml:boundary_type
  - ml:creation_date
  - ml:verified_from
  - ml:author
  - ml:country_code
  - ml:admin1
  - ml:admin2
properties:
  ml:ml:boundary_type:
    type: string
  ml:creation_date:
    type: date-time
  ml:verified_from:
    type: date-time
  ml:author:
    type: string
  ml:country_code:
    type: string
  ml:admin1:
    type: string
  ml:admin2:
    type: string
